repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/prettier/prettier
  rev: 2.4.1
  hooks:
  - id: prettier
    types: [javascript, json, markdown, css, yaml]
    exclude: "server/migrations/.*"

- repo: local
  hooks:
  - id: lint-backend
    name: Backend lint
    entry: python manage.py lint
    language: system
    pass_filenames: false
    types: [python]

- repo: local
  hooks:
  - id: lint-frontend
    name: Frontend lint
    entry: npx eslint --ext .js,.jsx,.ts,.tsx frontend
    language: system
    pass_filenames: false
    types: [javascript, typescript]
