# Generated by Django 4.2.4 on 2023-08-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_postal_code_alter_user_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='date_of_birth',
        ),
    ]
