# Generated by Django 4.2.4 on 2023-08-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_birthdate_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
