openapi: 3.0.0
info:
  title: Post API
  version: 1.0.0
paths:
  /api/posts:
    get:
      summary: Obtener todos los posts
      tags:
        - Post
      responses:
        "200":
          description: Posts obtenidos exitosamente.
    post:
      summary: Crear un nuevo post
      tags:
        - Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Título del post.
                  example: "Mi segundo post"
                content:
                  type: string
                  description: Contenido del post.
                  example: "Este es el contenido de mi segundo post."
                post_date:
                  type: string
                  format: date-time
                  description: Fecha de publicación del post.
                  example: "2023-08-02T10:00:00Z"
                photo:
                  type: string
                  description: URL de la foto relacionada con el post.
                  example: "https://example.com/photo.jpg"
                video:
                  type: string
                  description: URL del video relacionado con el post.
                  example: "https://example.com/video.mp4"
                usersCustomuserId:
                  type: integer
                  description: ID del usuario que crea el post.
                  example: 1
      responses:
        "201":
          description: Post creado exitosamente.

  /api/posts/{id}:
    get:
      summary: Obtener un post por ID
      tags:
        - Post
      parameters:
        - in: path
          name: id
          required: true
          description: ID del post a obtener.
          schema:
            type: integer
      responses:
        "200":
          description: Post obtenido exitosamente.
    put:
      summary: Actualizar un post existente por ID
      tags:
        - Post
      parameters:
        - in: path
          name: id
          required: true
          description: ID del post a actualizar.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Nuevo título del post.
                  example: "Nuevo título"
                content:
                  type: string
                  description: Nuevo contenido del post.
                  example: "Nuevo contenido del post."
                post_date:
                  type: string
                  format: date-time
                  description: Nueva fecha de publicación del post.
                  example: "2023-08-03T08:00:00Z"
                photo:
                  type: string
                  description: Nueva URL de foto relacionada con el post.
                  example: "https://newexample.com/photo.jpg"
                video:
                  type: string
                  description: Nueva URL de video relacionada con el post.
                  example: "https://newexample.com/video.mp4"
                usersCustomuserId:
                  type: integer
                  description: Nuevo ID del usuario relacionado con el post.
                  example: 2
      responses:
        "200":
          description: Post actualizado exitosamente.
    delete:
      summary: Eliminar un post por ID
      tags:
        - Post
      parameters:
        - in: path
          name: id
          required: true
          description: ID del post a eliminar.
          schema:
            type: integer
      responses:
        "204":
          description: Post borrado exitosamente.
