openapi: 3.0.0
info:
  title: Experiencia API
  version: 1.0.0
paths:
  /api/experience:
    post:
      summary: Crear una nueva experiencia
      tags:
        - Experience
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                job_position:
                  type: string
                  description: Cargo en el trabajo.
                  example: "Software Engineer"
                company_name:
                  type: string
                  description: Nombre de la empresa.
                  example: "TechCo"
                ubication:
                  type: string
                  description: Ubicación del trabajo.
                  example: "New York"
                sector:
                  type: string
                  description: Sector de la empresa.
                  example: "Technology"
                description:
                  type: string
                  description: Descripción de la experiencia.
                  example: "Worked on web application development."
                start_date:
                  type: string
                  format: date
                  description: Fecha de inicio de la experiencia.
                  example: "2022-01-01"
                end_date:
                  type: string
                  format: date
                  description: Fecha de finalización de la experiencia.
                  example: "2022-12-31"
                typesOfEmploymentId:
                  type: integer
                  description: ID del tipo de empleo.
                  example: 3
                typesOfUbicationId:
                  type: integer
                  description: ID del tipo de ubicación.
                  example: 2
                usersCustomuserId:
                  type: integer
                  description: ID del usuario personalizado.
                  example: 4
      responses:
        "201":
          description: Experiencia creada exitosamente.
    get:
      summary: Obtener todas las experiencias
      tags:
        - Experience
      responses:
        "200":
          description: Experiencias obtenidas exitosamente.
  /api/experience/{id}:
    put:
      summary: Actualizar una experiencia existente
      tags:
        - Experience
      parameters:
        - in: path
          name: id
          required: true
          description: ID de la experiencia a actualizar.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                job_position:
                  type: string
                  description: Nuevo cargo en el trabajo.
                  example: "Senior Software Engineer"
                company_name:
                  type: string
                  description: Nuevo nombre de la empresa.
                  example: "TechGurus"
                ubication:
                  type: string
                  description: Nueva ubicación del trabajo.
                  example: "San Francisco"
                sector:
                  type: string
                  description: Nuevo sector de la empresa.
                  example: "Tech"
                description:
                  type: string
                  description: Nueva descripción de la experiencia.
                  example: "Led development of web applications."
                start_date:
                  type: string
                  format: date
                  description: Nueva fecha de inicio de la experiencia.
                  example: "2023-03-15"
                end_date:
                  type: string
                  format: date
                  description: Nueva fecha de finalización de la experiencia.
                  example: "2023-12-31"
                typesOfEmploymentId:
                  type: integer
                  description: Nuevo ID del tipo de empleo.
                  example: 6
                typesOfUbicationId:
                  type: integer
                  description: Nuevo ID del tipo de ubicación.
                  example: 1
                usersCustomuserId:
                  type: integer
                  description: Nuevo ID del usuario personalizado.
                  example: 2
      responses:
        "200":
          description: Experiencia actualizada exitosamente.
