openapi: 3.0.0
info:
  title: Likes API
  version: 1.0.0
paths:
  /api/likes:
    post:
      summary: Crear un nuevo like
      tags:
        - Likes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usersCustomuserId:
                  type: integer
                  description: ID del usuario que da el like.
                  example: 5
                PostId:
                  type: integer
                  description: ID del post al que se da el like.
                  example: 1
      responses:
        "201":
          description: Like creado exitosamente.
