openapi: 3.0.0
info:
  title: Comments API
  version: 1.0.0
paths:
  /api/comments:
    post:
      summary: Crear un nuevo comentario
      tags:
        - Comments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Contenido del comentario.
                  example: "Último comentario de prueba."
                date_comment:
                  type: string
                  format: date-time
                  description: Fecha y hora del comentario.
                  example: "2023-08-02T12:30:00Z"
                usersCustomuserId:
                  type: integer
                  description: ID del usuario que realiza el comentario.
                  example: 5
                PostId:
                  type: integer
                  description: ID del post al que se refiere el comentario.
                  example: 3
      responses:
        "201":
          description: Comentario creado exitosamente.
