swagger: "2.0"
info:
  version: "1.0.0"
  title: Job Applications API
paths:
  /jobAplication/{id}:
    get:
      tags:
        - Jobs Applications
      summary: Obtener una aplicación de empleo por ID de usuario
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID del usuario para obtener sus aplicaciones de empleo
      responses:
        200:
          description: Éxito. Devuelve una aplicación de empleo.
          schema:
            $ref: "#/definitions/JobApplication"
  /jobAplication:
    post:
      tags:
        - Jobs Applications
      summary: Crear una nueva aplicación de empleo
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Datos de la nueva aplicación de empleo
          required: true
          schema:
            $ref: "#/definitions/JobApplication"
      responses:
        201:
          description: Éxito. La aplicación de empleo se ha creado correctamente.
  /jobAplication/{userId}/{jobId}:
    delete:
      tags:
        - Jobs Applications
      summary: Eliminar una aplicación de empleo por ID de usuario y ID de empleo
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
          description: ID del usuario propietario de la aplicación de empleo
        - name: jobId
          in: path
          required: true
          type: integer
          description: ID del empleo asociado a la aplicación de empleo
      responses:
        204:
          description: Éxito. La aplicación de empleo se ha eliminado correctamente.
definitions:
  JobApplication:
    type: object
    properties:
      id:
        type: integer
      cv:
        type: string
      resume:
        type: string
      reason_for_interest:
        type: string
      usersCustomuserId:
        type: integer
      JobId:
        type: integer
