swagger: "2.0"
info:
  version: "1.0.0"
  title: Job Preferences API
basePath: /api/jobPreferences
tags:
  - name: Job Preferences
    description: Operaciones relacionadas con las preferencias de empleo de los usuarios
paths:
  /jobPreferences/{userId}:
    get:
      tags:
        - Job Preferences
      summary: Obtener todas las preferencias de empleo de un usuario
      parameters:
        - name: userId
          in: path
          description: ID del usuario para el cual se obtendrán las preferencias de empleo
          required: true
          type: integer
      responses:
        200:
          description: Preferencias de empleo del usuario obtenidas con éxito
        404:
          description: Preferencias de empleo no encontradas para el usuario
    post:
      tags:
        - Job Preferences
      summary: Crear una nueva preferencia de empleo para un usuario
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Datos de la preferencia de empleo a crear
          required: true
          schema:
            $ref: "#/definitions/CreateJobPreferenceInput"
      responses:
        201:
          description: Preferencia de empleo creada con éxito
        400:
          description: Datos de preferencia de empleo no válidos

  /jobPreferences/{userId}/{jobId}:
    delete:
      tags:
        - Job Preferences
      summary: Eliminar una preferencia de empleo de un usuario para un trabajo específico
      parameters:
        - name: userId
          in: path
          description: ID del usuario del cual se eliminará la preferencia
          required: true
          type: integer
        - name: jobId
          in: path
          description: ID del empleo (trabajo) que se desea eliminar de las preferencias del usuario
          required: true
          type: integer
      responses:
        204:
          description: Preferencia de empleo eliminada exitosamente
        404:
          description: Preferencia de empleo no encontrada para el usuario o el trabajo

definitions:
  CreateJobPreferenceInput:
    type: object
    properties:
      data_preference:
        type: string
        format: date-time
        description: Fecha y hora de preferencia de empleo
        example: "2023-08-02T14:30:00"
      usersCustomuserId:
        type: integer
        description: ID del usuario
        example: 1
      JobId:
        type: integer
        description: ID del empleo (trabajo)
        example: 2
